#!/bin/sh

if command -v dropbox > /dev/null;
then
	dropbox &
fi

export PROTON_USE_WINED3D=1

background -f ${HOME}/img/fangorn.jpg

VBoxClient-all &
xmodmap ~/.Xmodmap
xbindkeys -p &
numlockx &
eval $(ssh-agent)
xrdb ~/.Xresources
i3

