export KUBECONFIG="${HOME}/.kube/config"

# ctrl + k, ctrl + a, etc., have issues in tmux with zsh. Fix it.
bindkey -e

export HISTTIMEFORMAT="[%F %T] "
export SAVEHIST=100000000
export HISTFILE=$HOME/.zsh_history
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt SHARE_HISTORY

# Append system paths to end of $PATH
PATH=$PATH:/opt/bin
PATH=$PATH:/opt/local/bin
PATH=$PATH:/opt/local/sbin
PATH=$PATH:/sbin
PATH=$PATH:/usr/local/bin

# Prepend trusted user paths to start of $PATH
PATH=$HOME/bin:$PATH
PATH=$HOME/.local/bin:$PATH

# Append untrusted paths to the end of $PATH
PATH=$PATH:$HOME/.yarn/bin

# Go
PATH=$HOME/src/go/bin:$PATH
export GOPATH=$HOME/src/go
if go -v >/dev/null 2>&1
then
	PATH=$PATH:$(go env GOPATH)/bin
fi

# Python
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv > /dev/null
then
	eval "$(pyenv init --path)"
fi

# Ruby
export PATH="$HOME/.rbenv/bin:$PATH"
if command -v rbenv > /dev/null
then
	eval "$(rbenv init -)"
fi

# Nodenv
export PATH="$HOME/.nodenv/bin:$PATH"
if command -v nodenv > /dev/null
then
	eval "$(nodenv init -)"
fi

# Rustup/Rust/cargo
PATH=$PATH:$HOME/.cargo/bin

if command -v exa > /dev/null
then
	alias ls="exa -g"
fi

if [ -f "${HOME}/.zshrc.local" ]
then
	source "${HOME}/.zshrc.local"
fi

# Set up the prompt

autoload -Uz promptinit
promptinit
prompt adam1

setopt histignorealldups sharehistory

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

