ZSH="${ZSH:=${HOME}/.oh-my-zsh/}"

plugins=(direnv git)

ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh
if [ ! -d "${ZSH_CACHE_DIR}" ]
then
	mkdir "${ZSH_CACHE_DIR}"
fi

export KUBECONFIG="${HOME}/.kube/config"

ZSH_COMPDUMP="${ZSH_CACHE_DIR}/.zcompdump-${HOST/.*/}-${ZSH_VERSION}"
#ZSH_THEME="random"
#ZSH_THEME_RANDOM_CANDIDATES=( "muse" )
ZSH_THEME="will"

source ${ZSH}/oh-my-zsh.sh

# ctrl + k, ctrl + a, etc., have issues in tmux with zsh. Fix it.
bindkey -e

export HISTTIMEFORMAT="[%F %T] "
export SAVEHIST=100000000
export HISTFILE=$HOME/.zsh_history
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt SHARE_HISTORY

# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Append system paths to end of $PATH
PATH=$PATH:/opt/bin
PATH=$PATH:/opt/local/bin
PATH=$PATH:/opt/local/sbin
PATH=$PATH:/sbin
PATH=$PATH:/usr/local/bin

# Prepend trusted user paths to start of $PATH
PATH=$HOME/bin:$PATH
PATH=$HOME/.local/bin:$PATH

# Append untrusted paths to the end of $PATH
PATH=$PATH:$HOME/.yarn/bin

# Go
PATH=$HOME/src/go/bin:$PATH
export GOPATH=$HOME/src/go
if go -v >/dev/null 2>&1
then
	PATH=$PATH:$(go env GOPATH)/bin
fi

# Python
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv > /dev/null
then
	eval "$(pyenv init --path)"
fi

# Ruby
export PATH="$HOME/.rbenv/bin:$PATH"
if command -v rbenv > /dev/null
then
	eval "$(rbenv init -)"
fi

# Nodenv
export PATH="$HOME/.nodenv/bin:$PATH"
if command -v nodenv > /dev/null
then
	eval "$(nodenv init -)"
fi

if command -v exa > /dev/null
then
	alias ls="exa -g"
fi

if [ -f "${HOME}/.zshrc.local" ]
then
	source "${HOME}/.zshrc.local"
fi
